/**
 * Axe-Fx II agent guidance — migrated from the long device-namespaced
 * tool descriptions in `src/fractal/axe-fx-ii/tools/{discovery,params,
 * navigation,preset}.ts`.
 *
 * v0.3 removed the device-namespaced tool surface; the LLM no longer
 * sees these guidance blocks through tool descriptions. They surface
 * instead via `describe_device({ port: 'axe-fx-ii' }).agent_guidance`.
 */

export const AXEFX2_AGENT_GUIDANCE: Readonly<Record<string, string>> = {
  note_response: [
    'play_note / play_chord on the Axe-Fx II are typically SILENT. The II',
    'is an audio processor for guitar input; MIDI Note On/Off bytes are',
    'accepted but produce no sound on normal patches. The Synth block,',
    'when placed in the active preset, responds to incoming MIDI notes —',
    'so play_note can be audible if and only if the working buffer holds',
    'a Synth-block preset. The unified tool always sends the bytes',
    'successfully; whether sound emerges depends on the preset.',
  ].join(' '),

  diagnostic_isolation: [
    'When the user reports an unwanted artifact in a tone, isolate via',
    'set_bypass — toggle one block at a time and ask the user to play',
    'between toggles, before changing any param values. The Axe-Fx II',
    'has no general MIDI audition path (see note_response above), so the',
    'human-in-the-loop is the test signal. Bulk edits during diagnosis',
    'hide which change mattered; isolation surfaces the source one',
    'round-trip at a time. Batching is correct for confident builds;',
    'isolation is the right tool for chasing artifacts.',
  ].join(' '),

  channel_model: [
    'Axe-Fx II blocks expose two channels — X and Y — NOT the AM4 four',
    '(A/B/C/D). Scenes pick which channel each block uses (plus per-block',
    'bypass). When the user says "scene 2", that\'s a selector for per-',
    'block channel + bypass state within the current preset; it doesn\'t',
    'duplicate the params (channels hold the params, scenes pick which',
    'channel each block uses).',
  ].join(' '),

  preset_location_format: [
    'Axe-Fx II presets are addressed by integer slot index 0..16383 on',
    'the wire. The FRONT PANEL displays preset numbers as wire+1 (front-',
    'panel #1 is wire 0). The user usually thinks in front-panel numbers',
    '— pass the same integer the user names; describe_device reports the',
    'preset_location_format.',
  ].join(' '),

  param_addressing: [
    'Params are addressed by (block, name) where `block` resolves on',
    'block instance display name ("Amp 1", "Delay 1") OR effectId',
    'integer, and `name` is the snake-case param key (effect_type, gain,',
    'mix, etc.). All instances of the same block group (e.g. Amp 1 / Amp',
    '2) share the same param table — list_params per group covers every',
    'instance.',
  ].join(' '),

  set_param_interpret: [
    'Numeric set_param values are interpreted in display units by default.',
    'For wire-level writes (raw 0..65534), some param types lack a',
    'calibrated display range and the unified set_param accepts the wire',
    'integer directly — see list_params for the param\'s controlType.',
    'Enum / select params accept the display name string OR the wire',
    'index. The relaxed matcher disambiguates partial names; the ack',
    'reports the full resolved name in parentheses.',
  ].join(' '),

  lineage_matchvia: [
    'lookup_lineage returns a `matchVia` field naming the lookup-path',
    'used to find the wiki entry (NOT a confidence rating on the data):',
    '  direct         — exact name match. Trust the data.',
    '  abbrev-expand  — Axe-Fx II truncates words to fit its 16-char',
    '                   display ("NRML"→"NORMAL", "MDRN"→"MODERN").',
    '                   Same model, different label. Trust the data.',
    '  reverb-swap    — reverb labels invert word order ("MEDIUM HALL"',
    '                   matches wiki "Hall, Medium"). Trust the data.',
    '  prefix         — Axe-Fx II uses a family-head abbreviation that',
    '                   prefixes a more specific wiki entry. Family-',
    '                   level lineage is solid; specifics approximate.',
    '  unmatched      — no wiki record. Model exists in firmware, but',
    '                   lineage prose isn\'t sourced.',
    'Do NOT hedge on direct / abbrev-expand / reverb-swap — those are',
    'known-good display-string conventions. Hedge only on prefix /',
    'unmatched, or when the record\'s `flags` array surfaces a substantive',
    'data-quality issue (cross-attributed forum quotes, inherited basedOn).',
  ].join(' '),

  lineage_flags: [
    'Substantive lineage flags to surface to the user:',
    '  INHERITED — basedOn / tubes / cab were back-filled from a sibling',
    '    amp record. For amp-family siblings (Plexi 50W Normal/High) this',
    '    is fine; for non-sibling inheritance basedOn might be wrong.',
    '  Forum quotes naming a different amp family than the record — known',
    '    AM4 wiki-parser bug where cross-cutting "Regarding the following',
    '    X models" prose attaches to the prior entry. Filter; don\'t',
    '    surface as authoritative.',
    'Block coverage: amp (259 enum / 196 matched), drive (36 / 34),',
    'reverb (43 / 25), delay (18 / 17). Compressor / chorus / flanger /',
    'phaser / wah are AM4-only for now.',
  ].join(' '),

  save_intent_required: [
    'SAVE INTENT REQUIRED: call save / persist tools (apply_preset with',
    'target_location, save_preset) ONLY when the user has explicitly asked',
    'to save / persist / store / keep the preset. apply_preset without',
    'target_location is reversible (switch presets to discard); save is',
    'not. When in doubt, apply without target_location and ask whether to',
    'persist.',
  ].join(' '),

  apply_preset_fresh_vs_tweak: [
    'TWEAK vs FRESH: apply_preset REPLACES the working-buffer layout. If',
    'the user says "tweak my current tone", call set_param / set_block /',
    'set_bypass for the targeted change instead. apply_preset is for fresh',
    'designs ("build me a clean tone").',
  ].join(' '),

  pitch_block: [
    'PITCH BLOCK — read this before building any harmonizer / detune /',
    'whammy / arpeggiator preset. The pitch block is the single most',
    'mode-dependent block on the Axe-Fx II and a naïve set_param sequence',
    'will silence the signal or pin the harmony to an unmusical extreme',
    '(Session 88 founder feedback: 20-minute harmonized-lead session,',
    "first try produced an 'extremely high' harmony because voice_1_harmony",
    'was treated as a +27-semitone offset).',
    '',
    '== Effect-type choice ==',
    'pitch.effect_type picks the algorithm and decides what every other',
    'param means. The two harmonizer modes:',
    '  • FIXED HARM  — chromatic. voice_N_harmony is a semitone offset.',
    '                  Sounds parallel (always +3 semitones).',
    '  • INTEL HARM  — diatonic. voice_N_harmony is a SCALE DEGREE (1=',
    '                  unison, 3=third, 5=fifth, 7=seventh). Needs key +',
    '                  scale. This is what classic harmonized leads use',
    "                  (Maiden, Boston, 'Hotel California').",
    'For "harmony in E minor" the right answer is almost always INTEL HARM',
    'with key=E, scale="AEOLIAN MIN", voice_1_harmony=3 (display) which',
    "is wire 26 on the founder's Q8.02 firmware (label echoes as '3').",
    '',
    '== voice_N_harmony wire encoding (hardware-verified Session 88) ==',
    'The descriptor lists displayMin=0, displayMax=48, but the device',
    'treats this param as a near-direct integer index, NOT a linear',
    'scale across 0..65534. Hardware ground truth:',
    '  wire 24 → label "1"   (unison center)',
    '  wire 25 → label "2"   (+1 step)',
    '  wire 26 → label "3"   (+3 semitones — minor 3rd up in INTEL HARM)',
    '  wire 27 → label "4"',
    'Formula for the wire integer: `wire = 23 + scale_degree`.',
    'In INTEL HARM mode pass the display value as a small integer 1..N',
    'and the dispatcher\'s linear display→wire scaling lands you in the',
    'right ballpark for testing — but READ-BACK is required because the',
    'display calibration here is approximate. Pass display=3 and check',
    'get_param echoes label "3" before declaring success.',
    '',
    '== Voice 2 mute discipline ==',
    'voice_2_level defaults non-zero on most factory pitch presets — if',
    'you only want ONE harmony voice, explicitly set voice_2_level=0',
    "(wire 0 = 0%). Skipping this is why the founder's first harmonized",
    "lead had a dissonant minor-2nd clash they didn't ask for.",
    '',
    '== Opaque-percent / opaque-dB params (mix, level, voice_N_level) ==',
    'These are `unit: "opaque"` — set_param writes the wire integer',
    'DIRECTLY, no display scaling. Cheat sheet from hardware-verified',
    'reads:',
    '  pitch.mix    wire 16384 = 25%    wire 32767 = 50%    wire 65534 = 100%',
    '  pitch.level  wire 32767 = -30 dB wire 49152 = -5 dB',
    '               wire 52428 ≈ 0 dB UNITY  wire 65534 = +20 dB',
    '  pitch.voice_N_level  wire 0 = 0% (muted)  wire 65534 = 100%',
    'Sending `value: 50` to pitch.mix sets it to 0.076 %, not 50 % — and',
    'sending `value: 0` to pitch.level mutes the entire block.',
    '',
    '== Typical harmonized-lead config (one-shot set_params payload) ==',
    'After apply_preset places the block:',
    '  pitch.effect_type   = "INTEL HARM"',
    '  pitch.key           = "E"  (or whatever)',
    '  pitch.scale         = "AEOLIAN MIN"  (or whatever)',
    '  pitch.voice_1_harmony = 3       // scale degree, READ BACK to verify',
    '  pitch.voice_2_level = 0         // wire 0 = mute the second voice',
    '  pitch.mix           = 32767     // wire 50% — 1:1 dry/wet',
    '  pitch.level         = 52428     // wire ≈ 0 dB unity gain',
  ].join('\n'),
};
